import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SendQuestion from "./components/sendQuestion";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <SendQuestion url="çünkü lütfen" text="nolur bize soru gönder"/>
        <Header />
        {children}</body>
    </html>
  );
}
